# Generated by Django 6.0.5 on 2026-05-21 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('flow_volume', models.FloatField(help_text='Flow volume in liters per second')),
                ('is_open', models.BooleanField(default=False)),
                ('drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensers', to='drinks.drink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispenserUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('liters_served', models.FloatField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='dispensers.dispenser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
